#!/bin/bash

tests(){
    docker run --rm -it -v "$PWD:/app" py3.9-poetry \
        poetry lock --no-update && \
        poetry install && \
        poetry run python -m pytest --cov "$@"
}

ipython(){
    docker run --rm -it -v "$PWD:/app" py3.9-poetry \
        poetry lock --no-update && \
        poetry install && \
        poetry run ipython
}

isort() {
    docker run --rm -it -v "$PWD:/app" py3.9-poetry \
        poetry lock --no-update && \
        poetry install && \
        poetry run isort .
}

black() {
    docker run --rm -it -v "$PWD:/app" py3.9-poetry \
        poetry lock --no-update && \
        poetry install && \
        poetry run black .
}

mypy() {
    docker run --rm -it -v "$PWD:/app" py3.9-poetry \
        poetry lock --no-update && \
        poetry install && \
        poetry run mypy .
}

dev() {
    docker run --rm -it -v "$PWD:/app" py3.9-poetry \
        poetry lock --no-update && \
        poetry install && \
        poetry shell
}


ARGS="$@"
"$@"
